//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UĞUR_PAZARLAMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UgurPazarlamaEntities : DbContext
    {
        public UgurPazarlamaEntities()
            : base("name=UgurPazarlamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_DEPO> TBL_DEPO { get; set; }
        public virtual DbSet<TBL_ILCELER> TBL_ILCELER { get; set; }
        public virtual DbSet<TBL_ILLER> TBL_ILLER { get; set; }
        public virtual DbSet<TBL_KATEGORILER> TBL_KATEGORILER { get; set; }
        public virtual DbSet<TBL_MARKALAR> TBL_MARKALAR { get; set; }
        public virtual DbSet<TBL_MUSTERILER> TBL_MUSTERILER { get; set; }
        public virtual DbSet<TBL_PERSONELLER> TBL_PERSONELLER { get; set; }
        public virtual DbSet<TBL_SATIS> TBL_SATIS { get; set; }
        public virtual DbSet<TBL_STATULER> TBL_STATULER { get; set; }
        public virtual DbSet<TBL_URUN> TBL_URUN { get; set; }
    }
}
