//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UĞUR_PAZARLAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUN()
        {
            this.TBL_DEPO = new HashSet<TBL_DEPO>();
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public short BARKODNO { get; set; }
        public string AD { get; set; }
        public Nullable<byte> MARKA { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<byte> STOK { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> SATISFIYAT { get; set; }
        public string FOTOGRAF { get; set; }
        public string OZELLIKLER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEPO> TBL_DEPO { get; set; }
        public virtual TBL_KATEGORILER TBL_KATEGORILER { get; set; }
        public virtual TBL_MARKALAR TBL_MARKALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
