//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UĞUR_PAZARLAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STATULER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STATULER()
        {
            this.TBL_PERSONELLER = new HashSet<TBL_PERSONELLER>();
        }
    
        public byte ID { get; set; }
        public string STATUAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERSONELLER> TBL_PERSONELLER { get; set; }
    }
}
