//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UĞUR_PAZARLAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPO
    {
        public byte ID { get; set; }
        public Nullable<short> BARKODNO { get; set; }
        public string AD { get; set; }
        public string TARIH { get; set; }
        public Nullable<byte> ADET { get; set; }
        public Nullable<decimal> ALISFIYAT { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
    
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
