//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UĞUR_PAZARLAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATIS
    {
        public short ID { get; set; }
        public Nullable<short> URUN { get; set; }
        public Nullable<byte> MUSTERI { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public string TARIH { get; set; }
        public Nullable<short> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
    
        public virtual TBL_MUSTERILER TBL_MUSTERILER { get; set; }
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
